# -*- coding: utf-8 -*-
"""Data_Structures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-YGO0pv3wo2P5wv1OT7hhPWbejjkPCm
"""

# What Are Data Structures?
# Data structures are ways of organizing and storing data so that they
# can be accessed and modified efficiently.

# Why Should You, as a Developer, Learn Data Structures?
# The right data structure makes your code faster and more efficient.
# Most coding interviews and real-world challenges require solid data structure knowledge.
# Helps you organize code better and avoid messy or repeated logic.

# Python provides several built-in data structures
# List
# Tuple
# Set
# Dictionaries

# LIST
# LIST IS A COLLECTION OF DATA VALUES / ELEMENTS
# LIST IS DENOTED BY USING [] / list()
# LIST IS MUTABLE [CHANGEABLE / MODIFIABLE / DELETION / UPDATION]
# LIST ALLOWS US TO HAVE DUPLICATE ELEMENTS

# CREATE A LIST

list1 = [1,2,3,4,5]
print(type(list1))

list2 = list(['a','b','c','d'])
print(type(list2))

list3 = []           # empty list
print(type(list3))

# indexing and slicing
list1 = [10,20,30,40,50,60,70,80]
print(list1)

# 10  20   30    40    50    60    70    80
# 0   1    2     3     4      5    6      7
# -8  -7   -6    -5    -4     -3   -2     -1

print(list1[1])
print(list1[-1])

print(list1[1:6])
print(list1[1:6:2])
print(list1[::-1])

#list is iterable
list1 = [10,20,30,40,50,60,70,80]
for i in list1:
  if i%4==0:
    print(i)

# Print the elements of list along with index numbers
list1 = [10,20,30,40,50,60,70,80]
# len() : used to count the number of elements in a List
print(len(list1))

for i in range(len(list1)):                   # range(8)  --> 0 1 2 3 4 5 6 7
  print(f'Index {i} : {list1[i]}')            #  i --> 0    list1[2]10

# enumerate()  it will show elements along with index numbers
for i,e in enumerate(list1):
  print(f'Index {i} : {e}')

# enumerate()  it will show elements along with index numbers
for i in enumerate(list1):
  print(i)

# LIST BUILT-IN METHODS

list1 = [10,20,30,40,50,60,70,80,90,100]
print('Original List :',list1)

# a.) append(value)
# used to add a new element at the END of the List
list1.append(110)
print('After Append :',list1)

# b.) insert(indexNumber,value)
# used to add a new element at any specific position in List
list1.insert(0,200)
print('After Insert :',list1)

# f.) clear()
# used to remove the elements from List

list1.clear()
print('After Clear :',list1)

del list1

# c.) pop(indexNumber)
# used to delete an element from list
list1.pop(0)
print('After Pop :',list1)

# d.) pop()
# if no index number was given , it will delete the Last element
list1.pop()
print('After Pop :',list1)

# e.) remove(value)
# it will delete the specified value
list1.remove(90)
print('After Remove :',list1)

# list = [10,20,30,10,10,10,40,50]
# list.remove(10) ? which 10 it will delete
# it will delete the first occurence of 10
# list = [20,30,10,10,10,40,50]

# f.) sort()
list1 = [67,32,19,80,12,17,45,26,46,78]
list1.sort()   # ascending order
print(list1)

list1 = [67,32,19,80,12,17,45,26,46,78]
list1.sort(reverse=True)   # descending order
print(list1)

# g.) reverse()
list1 = [67,32,19,80,12,17,45,26,46,78]
list1.reverse()  # [::-1]
print(list1)

# TUPLE
# TUPLE IS A COLLECTION OF DATA VALUES / ELEMENTS
# TUPLE IS DENOTED BY USING () / tuple()
# TUPLE IS IMMUTABLE
# TUPLE ALLOWS US TO HAVE DUPLICATE ELEMENTS

# CREATE A TUPLE

t1 = (1,2,3,4,5)
print(type(t1))

t2 = tuple((1,2,3,4,5))
print(type(t2))

t3 = ()
print(type(t3))

# How to create a tuple having one element
tup11 = (45,)
print(type(tup11))

# Tuple is Immutable
t1 = (10,20,30,40)
print(t1)
t1[1] = 200
print(t1)

# len()
t1 = (10,20,30,40,10,10,10,50,60,70,10,80)
print(len(t1))
# count() print the total occurence of specified value
print(t1.count(10))
# index() helps you to get the index number
print(t1.index(70))

# SET
# SET IS AN UNORDERED COLLECTION OF DATA VALUES
# SET IS DENOTED BY USING {} /  set()
# SET DOES NOT ALLOW DUPLICATE RECORDS

set1 = {10,20,30,40,50}
print(type(set1))

set2 = set((10,20,30,40,50))
print(type(set2))

set3 = set()
print(type(set3))

ist1 = [10,20,10,30,40,10,50,60,20,30,50,70]
# WAP to print the no. of unique elements in a List
print('no. of unique elements :',set(list1))
print('no. of unique elements :',len(set(list1)))

list1 = [10,20,10,30,40,10,50,60,20,30,50,70]
empty_list = []
for i in list1:                                          #  i --> 30
  if i not in empty_list:                                 # 30 does not exist in []
    empty_list.append(i)                                   # [10,20,30]
print('no. of unique elements :',len(empty_list))

!pip install ordered-set

from ordered_set import OrderedSet
str1 = 'abracadabra'
print(set(str1))
print(OrderedSet(str1))

set1 = OrderedSet((10,20,30,40,10,10,50,60))
print(set1)

# DICTIONARIES
# DICTIONARY USED TO HOLD INFORMATION IN A KEY:VALUE PAIR
# DICTIONARY IS DENOTED BY USING {}
# DICTIONARY IS MUTABLE IN NATURE

emp_info = {'id':101 , 'name':'John' , 'age':32 , 'sal':6700 ,
            'email':'j@gmail.com' , 'city':'klang' , 'dept':'IT'}

print(type(emp_info))
print(emp_info)
print(emp_info["sal"])
print(emp_info["dept"])
print(emp_info.get("name"))

emp_info = {'id':[101,102,103],
            'name':['John','Alex','Smith'],
            'dept':['IT','HR','FN']}
print(emp_info)
print(emp_info["id"][0], emp_info["name"][0] , emp_info["dept"][0])