# -*- coding: utf-8 -*-
"""Matplotlib1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LpdDuj5WS-c-AcXBKrxS4yQLcCb7KH3K
"""

# Data Visualization
# Matplotlib
# https://matplotlib.org/

# Data visualization is the representation of data through use of common graphics,
# such as charts, plots, infographics and even animations.
# The primary goal of data visualization is to make data more accessible and
# easier to interpret, allowing users to identify patterns, trends, and outliers quickly.

# Matplotlib is a comprehensive library for creating static, animated,
# and interactive visualizations in Python.
# Matplotlib makes easy things easy and hard things possible.

# You can generate plots, histograms, power spectra, bar charts, errorcharts,
# scatterplots, etc., with just a few lines of code.

# The matplotlib library contains several modules. The matplotlib.pyplot module is
# designed to create colorful plots.