# -*- coding: utf-8 -*-
"""My_Python2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Sf71w2nsJoWLmErW6uumiG63pVkHxKI
"""

'''
Temperature Converter

Write a Python program to convert temperatures to and from Celsius and Fahrenheit.

[ Formula : c/5 = f-32/9 [ where c = temperature in celsius and f = temperature in fahrenheit ]

Expected Output :

60°C is 140 in Fahrenheit
45°F is 7 in Celsius
'''

# Temperature Converter

temp = input("Input the temperature you like to convert? (e.g., 45F, 102C): ")

degree = int(temp[:-1])
check = temp[-1].upper()

if check == "C":
    result = int((degree * 9) / 5 + 32)
    print(f"{degree}°C is {result} in Fahrenheit")
elif check == "F":
    result = int((degree - 32) * 5 / 9)
    print(f"{degree}°F is {result} in Celsius")
else:
    print("Invalid input! Please enter temperature with C or F.")

'''
Count Even and Odd Numbers

Write a Python program to count the number of even and odd numbers in a series of numbers

Sample numbers : numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)

Expected Output :

Number of even numbers : 5
Number of odd numbers : 4
'''
# Count Even and Odd Numbers

numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)

even_count = 0
odd_count = 0

for num in numbers:
    if num % 2 == 0:
        even_count += 1
    else:
        odd_count += 1

print("Number of even numbers:", even_count)
print("Number of odd numbers:", odd_count)

'''
Fibonacci Series Between 0 and 50

Write a Python program to get the Fibonacci series between 0 and 50.

Note : The Fibonacci Sequence is the series of numbers :

0, 1, 1, 2, 3, 5, 8, 13, 21, ....
Every next number is found by adding up the two numbers before it.

Expected Output : 1 1 2 3 5 8 13 21 34
'''
# Fibonacci Series Between 0 and 50

x, y = 0, 1

while y < 50:
    print(y, end=" ")
    x, y = y, x + y

'''
FizzBuzz Variation

Write a Python program that iterates the integers from 1 to 50. For multiples of three print "Fizz" instead of the number and for multiples of five print "Buzz". For numbers that are multiples of three and five, print "FizzBuzz".

Sample Output :

fizzbuzz
1
2
fizz
4
buzz
'''

# FizzBuzz Variation
# Iterate through numbers from 1 to 50
for num in range(1, 51):
    # Check if the number is divisible by both 3 and 5
    if num % 3 == 0 and num % 5 == 0:
        print("fizzbuzz")
    # Check if the number is divisible only by 3
    elif num % 3 == 0:
        print("fizz")
    # Check if the number is divisible only by 5
    elif num % 5 == 0:
        print("buzz")
    # If not divisible by either 3 or 5, print the number itself
    else:
        print(num)

'''
Password Validity Checker

Write a Python program to check the validity of passwords input by users.

Validation :

At least 1 letter between [a-z] and 1 letter between [A-Z].
At least 1 number between [0-9].
At least 1 character from [$#@].
Minimum length 6 characters.
Maximum length 16 characters.
'''
# Password Validity Checker

import re

p = input("Input your password: ")
x = True

while x:
    if (len(p) < 6 or len(p) > 16):
        break
    elif not re.search("[a-z]", p):
        break
    elif not re.search("[A-Z]", p):
        break
    elif not re.search("[0-9]", p):
        break
    elif not re.search("[$#@]", p):
        break
    elif re.search("\s", p):
        break
    else:
        print("Valid Password")
        x = False
        break

'''
Dog Age in Dog Years

Write a Python program to calculate a dog's age in dog years.

Note: For the first two years, a dog year is equal to 10.5 human years. After that, each dog year equals 4 human years.

Expected Output:

Input a dog's age in human years: 15
The dog's age in dog's years is 73
'''

# # Request input from the user to provide a dog's age in human years and convert it to an integer
h_age = int(input("Input a dog's age in human years: "))


if h_age < 0:
    print("Age must be a positive number.")

elif h_age <= 2:
    # For the first two years, each human year equals 10.5 dog years
    dog_age = h_age * 10.5
else:
    # After two years, each human year equals 4 dog years
    dog_age = 21 + (h_age - 2) * 4

print("The dog's age in dog's years is", int(dog_age))

'''
Astrological Sign Finder

Write a Python program to display the astrological sign for a given date of birth.

Expected Output:

Input birthday: 15
Input month of birth (e.g. march, july etc): may
Your Astrological sign is : Taurus
'''

# Request input from the user for the day of birth and convert it to an integer, assigning it to the variable 'day'
day = int(input("Input birthday: "))

# Request input from the user for the month of birth and assign it to the variable 'month'
month = input("Input month of birth (e.g. march, july etc): ").lower()

# Determine the astrological sign based on the provided day and month

if month == 'december':
    sign = 'Sagittarius' if day <= 21 else 'Capricorn'
elif month == 'january':
    sign = 'Capricorn' if day <= 19 else 'Aquarius'
elif month == 'february':
    sign = 'Aquarius' if day <= 18 else 'Pisces'
elif month == 'march':
    sign = 'Pisces' if day <= 20 else 'Aries'
elif month == 'april':
    sign = 'Aries' if day <= 19 else 'Taurus'
elif month == 'may':
    sign = 'Taurus' if day <= 20 else 'Gemini'
elif month == 'june':
    sign = 'Gemini' if day <= 20 else 'Cancer'
elif month == 'july':
    sign = 'Cancer' if day <= 22 else 'Leo'
elif month == 'august':
    sign = 'Leo' if day <= 22 else 'Virgo'
elif month == 'september':
    sign = 'Virgo' if day <= 22 else 'Libra'
elif month == 'october':
    sign = 'Libra' if day <= 22 else 'Scorpio'
elif month == 'november':
    sign = 'Scorpio' if day <= 21 else 'Sagittarius'
else:
    sign = 'Invalid month entered.'

print("Your Astrological sign is:", sign)

'''
Chinese Zodiac Sign

Write a Python program to display the sign of the Chinese Zodiac for the given year in which you were born.

Expected Output:

Input your birth year: 1973
Your Zodiac sign : Ox
'''

# Request input from the user for the birth year and convert it to an integer, assigning it to the variable 'year'
year = int(input("Input your birth year: "))

# Determine the Chinese zodiac sign based on the provided birth year

# Check if the year corresponds to the Chinese zodiac sign 'Dragon'
if (year - 2000) % 12 == 0:
    sign = 'Dragon'
# Check if the year corresponds to the Chinese zodiac sign 'Snake'
elif (year - 2000) % 12 == 1:
    sign = 'Snake'
# Check if the year corresponds to the Chinese zodiac sign 'Horse'
elif (year - 2000) % 12 == 2:
    sign = 'Horse'
# Check if the year corresponds to the Chinese zodiac sign 'Goat'
elif (year - 2000) % 12 == 3:
    sign = 'Goat'
# Check if the year corresponds to the Chinese zodiac sign 'Monkey'
elif (year - 2000) % 12 == 4:
    sign = 'Monkey'
# Check if the year corresponds to the Chinese zodiac sign 'Rooster'
elif (year - 2000) % 12 == 5:
    sign = 'Rooster'
# Check if the year corresponds to the Chinese zodiac sign 'Dog'
elif (year - 2000) % 12 == 6:
    sign = 'Dog'
# Check if the year corresponds to the Chinese zodiac sign 'Pig'
elif (year - 2000) % 12 == 7:
    sign = 'Pig'
# Check if the year corresponds to the Chinese zodiac sign 'Rat'
elif (year - 2000) % 12 == 8:
    sign = 'Rat'
# Check if the year corresponds to the Chinese zodiac sign 'Ox'
elif (year - 2000) % 12 == 9:
    sign = 'Ox'
# Check if the year corresponds to the Chinese zodiac sign 'Tiger'
elif (year - 2000) % 12 == 10:
    sign = 'Tiger'
# If none of the above, assign the Chinese zodiac sign as 'Rabbit'
else:
    sign = 'Rabbit'

print("Your Zodiac sign:", sign)