# -*- coding: utf-8 -*-
"""My_Python1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AXFXwOjU2d3e4H4c3CxTIBVQkRjS7wdH
"""

#Python String capitalize() Method
#Definition: The capitalize() method returns a string where the first character is upper case, and the rest is lower case.

txt = "python is FUN!"
x = txt.capitalize()
print (x)

#Python String casefold() Method
#Definition: The casefold() method returns a string where all the characters are lower case.

txt = "Hello, And Welcome To My World!"
x = txt.casefold()
print(x)

#Python String count() Method
#Definition: The count() method returns the number of times a specified value appears in the string.

txt = "I love apples, apple are my favorite fruit"
x = txt.count("apple")
print(x)

#Python String endswith() Method
#Definition: The endswith() method returns True if the string ends with the specified value, otherwise False.

txt = "Hello, welcome to my world."
x = txt.endswith(".")
print(x)

#Python String find() Method
#Definition: The find() method finds the first occurrence of the specified value.

txt = "Hello, welcome to my world."
x = txt.find("e")
print(x)

#Python String islower() Method
#Definition: The islower() method returns True if all the characters are in lower case, otherwise False.

txt = "hello world!"
x = txt.islower()
print(x)

#Python String isupper() Method
#Definition: The isupper() method returns True if all the characters are in upper case, otherwise False.

txt = "THIS IS NOW!"
x = txt.isupper()
print(x)

#Python String lower() Method
#Definition: The lower() method returns a string where all characters are lower case.

txt = "Hello my FRIENDS"
x = txt.lower()
print(x)

#Python String upper() Method
#Definition: The upper() method returns a string where all characters are in upper case.

txt = "Hello my friends"
x = txt.upper()
print(x)

#Python String startswith() Method
#Definition: The startswith() method returns True if the string starts with the specified value, otherwise False.

txt = "Hello, welcome to my world."
x = txt.startswith("Hello")
print(x)

#Python String swapcase() Method
#Definition: The swapcase() method returns a string where all the upper case letters are lower case and vice versa.

txt = "Hello My Name Is PETER"
x = txt.swapcase()
print(x)

#Python String replace() Method
#Definition: The replace() method replaces a specified phrase with another specified phrase.

txt = "I like bananas"
x = txt.replace("bananas", "apples")
print(x)